language: objective-c
matrix:
  include:
    - osx_image: xcode7.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8

git:
  submodules: false
before_install:
  - git submodule update --init --recursive

script:
  - set -o pipefail
  - xcodebuild test -scheme Rex-Mac | xcpretty -c

notifications:
  email: false
