language: objective-c
matrix:
  include:
    - osx_image: xcode7.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8

git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.10/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"

script:
  - set -o pipefail
  - carthage bootstrap --platform Mac,iOS
  - xcodebuild test -scheme Rex-Mac
  - xcodebuild test -scheme Rex-iOS -sdk iphonesimulator

notifications:
  email: false
