language: objective-c
matrix:
  include:
    - osx_image: xcode7.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8

git:
  submodules: false
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"

script:
  - set -o pipefail
  - carthage bootstrap --platform mac,iphonesimulator
  - xcodebuild test -scheme Rex-Mac | xcpretty -c
  - xcodebuild test -scheme Rex-iOS -sdk iphonesimulator | xcpretty -c

notifications:
  email: false
